name: leibniz-chat

channels:
  - conda-forge
  - defaults
  
dependencies:
  - pip
  - pytest
  - python==3.9
  - python-dotenv
  - requests==2.28.1
  - pandas==1.5.0
  - notebook=6.4.12
  - pip:
    - pinecone-client
    - openai
    - langchain
    - pypdf
    - gradio
